```{r}
cat("\014")
rm(list = ls())
```

## working directory check

```{r}
getwd()

```
# set the working directory

```{r}
setwd("D:/R-code")
```

# load necessary library
```{r}
pacman::p_load(pacman,tensorflow,keras)
```



```{r}
cifar <- dataset_cifar10()
```

```{r}
class_names <- c('airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck')
index <- 1:30

```

```{r}
par(mfcol = c(5,6), mar = rep(1, 4), oma = rep(0.2, 4))
cifar$train$x[index,,,] %>% 
  purrr::array_tree(1) %>%
  purrr::set_names(class_names[cifar$train$y[index] + 1]) %>% 
  purrr::map(as.raster, max = 255) %>%
  purrr::iwalk(~{plot(.x); title(.y)})
```

```{r}
model <- keras_model_sequential() %>% 
  layer_conv_2d(filters = 32, kernel_size = c(3,3), activation = "relu", 
                input_shape = c(32,32,3)) %>% 
  layer_max_pooling_2d(pool_size = c(2,2)) %>% 
  layer_conv_2d(filters = 64, kernel_size = c(3,3), activation = "relu") %>% 
  layer_max_pooling_2d(pool_size = c(2,2)) %>% 
  layer_conv_2d(filters = 64, kernel_size = c(3,3), activation = "relu")
```
```{r}
summary(model)
```

Add Dense layers on top
```{r}
model %>% 
  layer_flatten() %>% 
  layer_dense(units = 64, activation = "relu") %>% 
  layer_dense(units = 10, activation = "softmax")
```

```{r}
summary(model)
```

Compile and train the model
```{r}
model %>% compile(
  optimizer = "adam",
  loss = "sparse_categorical_crossentropy",
  metrics = "accuracy"
)
```

```{r}
history <- model %>% 
  fit(
    x = cifar$train$x, y = cifar$train$y,
    epochs = 10,
    validation_data = unname(cifar$test),
    verbose = 2
  )
```

Evaluate the model
```{r}
plot(history)
```

```{r}
evaluate(model, cifar$test$x, cifar$test$y, verbose = 0)
```

Our simple CNN has achieved a test accuracy of over 65%. Not bad for a few lines of code!

